### ISSUE TITLE
bug in version 0.6.0 when run `kur data mnist.yml`, and a fix proposed

### ISSUE THREAD

**Issue by EmbraceLife** [deepgram/kur#56]
Error message: 

```
(dlnd-tf-lab)  ->kur data mnist.yml
Traceback (most recent call last):
  File "/Users/Natsume/miniconda2/envs/dlnd-tf-lab/bin/kur", line 11, in <module>
    load_entry_point('kur', 'console_scripts', 'kur')()
  File "/Users/Natsume/Downloads/kur_road/kur/kur/__main__.py", line 396, in main
    sys.exit(args.func(args) or 0)
  File "/Users/Natsume/Downloads/kur_road/kur/kur/__main__.py", line 185, in prepare_data
    keys = sorted(batch.keys())
AttributeError: 'str' object has no attribute 'keys'
```

I fixed it in the following way, see whether this is acceptable: 

replace [original line 167-168](https://github.com/deepgram/kur/blob/master/kur/__main__.py#L167) 

with the following lines: 
```
	for k in provider:
		provider = provider[k]
		for batch in provider:
			break
```

**Comment by ajsyp** [comment]
Thanks for pointing this out! Fixed in 480d411.
