### ISSUE TITLE
a bug in standard version Kur when `kur data mnist.yml`

### ISSUE THREAD

**Issue by EmbraceLife** [deepgram/kur#62]
by standard version, I mean installed by `pip install kur` 

There is a bug here when run `kur data mnist.yml`

```

In [3]: !kur data mnist.yml
Traceback (most recent call last):
  File "/Users/Natsume/miniconda2/envs/tempy3.4/bin/kur", line 11, in <module>
    sys.exit(main())
  File "/Users/Natsume/miniconda2/envs/tempy3.4/lib/python3.4/site-packages/kur/__main__.py", line 385, in main
    sys.exit(args.func(args) or 0)
  File "/Users/Natsume/miniconda2/envs/tempy3.4/lib/python3.4/site-packages/kur/__main__.py", line 174, in prepare_data
    keys = sorted(batch.keys())
AttributeError: 'str' object has no attribute 'keys'
```
It can be easily fixed, but I guess it can also be fixed by update standard version kur to development version kur

**Comment by ajsyp** [comment]
Yes, this was fixed in commit 480d411. The next PyPI release will roll it in.
