### ISSUE TITLE
not detecting gpu

### ISSUE THREAD

**Issue by nivedita** [deepgram/kur#79]
i get the following error when i try and run examples : 
[ERROR 2017-07-02 06:35:32,456 kur.backend.backend:131] Failed to find any available GPUs.gpu
Traceback (most recent call last):
  File "/home/nivedita/tensorflowGPU/bin/kur", line 11, in <module>
    sys.exit(main())
  File "/home/nivedita/tensorflowGPU/local/lib/python3.4/site-packages/kur/__main__.py", line 385, in main
    sys.exit(args.func(args) or 0)
  File "/home/nivedita/tensorflowGPU/local/lib/python3.4/site-packages/kur/__main__.py", line 62, in train
    func = spec.get_training_function()
  File "/home/nivedita/tensorflowGPU/local/lib/python3.4/site-packages/kur/kurfile.py", line 372, in get_training_function
    model = self.get_model(provider)
  File "/home/nivedita/tensorflowGPU/local/lib/python3.4/site-packages/kur/kurfile.py", line 158, in get_model
    backend=self.get_backend(),
  File "/home/nivedita/tensorflowGPU/local/lib/python3.4/site-packages/kur/kurfile.py", line 185, in get_backend
    (self.data.get('settings') or {}).get('backend')
  File "/home/nivedita/tensorflowGPU/local/lib/python3.4/site-packages/kur/backend/backend.py", line 271, in from_specification
    result = target(**params)
  File "/home/nivedita/tensorflowGPU/local/lib/python3.4/site-packages/kur/backend/keras_backend.py", line 79, in __init__
    super().__init__(*args, **kwargs)
  File "/home/nivedita/tensorflowGPU/local/lib/python3.4/site-packages/kur/backend/backend.py", line 132, in __init__
    **raise ValueError('Failed to find any available GPUs.')
ValueError: Failed to find any available GPUs.**

**when i run the following, i get GPU getting detected just fine :** 
import tensorflow as tf
sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))

Found device 0 with properties: 
name: Tesla K40c
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:01:00.0
Total memory: 11.17GiB
Free memory: 11.10GiB
2017-07-02 06:18:14.790586: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2017-07-02 06:18:14.790589: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2017-07-02 06:18:14.790596: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40c, pci bus id: 0000:01:00.0)
Device mapping:
/job:localhost/replica:0/task:0/gpu:0 -> device: 0, name: Tesla K40c, pci bus id: 0000:01:00.0
2017-07-02 06:18:14.826726: I tensorflow/core/common_runtime/direct_session.cc:265] Device mapping:
/job:localhost/replica:0/task:0/gpu:0 -> device: 0, name: Tesla K40c, pci bus id: 0000:01:00.0

i have the following cuda version :
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

my tensorflow also works fine. I am on python 3.4 

Kur Version: 0.6.0

**any help please? Really want this to work.  Thanks so much.**

**Comment by ajsyp** [comment]
I think this is closely related to #80. Let's merge conversation there?

**Comment by ajsyp** [comment]
Just for the record, commit d0b632b does, in fact, add a `skip_check` to the backend configuration, which can be used to skip the utilization check by setting it to "yes". This should fix the problem entirely (although you might need to explicitly set the device index, too).
